Repository ezsystems/ezplatform-richtext, pull requests merged in 2019-12, with the labels that each got.

#84 EZP-31130: Ensured content variable is always present in Custom Template Twig view
  src/lib/eZ/RichText/Converter/Render/Template.php
  tests/lib/eZ/RichText/Converter/Render/TemplateTest.php
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/024-template.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/025-templateInline.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/034-nestedTemplate.xml
Labels: DX, Improvement, QA approved

#89 EZP-31096: Custom toolbars in Alloy Editor
  src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
Labels: QA approved

#90 EZP-31207: Table header toolbar is added
  src/bundle/Resources/encore/ez.config.js
  src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-table-header.js
Labels: QA approved

#92 EZP-31046: Removed usage of `ezpublish.config.resolver.core`
  tests/bundle/DependencyInjection/Configuration/Parser/FieldType/RichTextTest.php
Labels: Feature, Ready for review

#80 EZP-31087: Fixed merging Online Editor extra_buttons semantic config
  composer.json
  src/bundle/DependencyInjection/Configuration.php
  tests/bundle/DependencyInjection/Configuration/ConfigurationTest.php
Labels: QA approved
