Repository ezsystems/ezplatform-richtext, pull requests merged in 2019-05, with the labels that each got.

#38 EZP-30315 [Travis] Standarize and clean up travis configurations across the repositories
  .travis.yml
Labels: Ready for review

#40 [CS] Locked php-cs-fixer at v2.15.x and aligned codebase
  composer.json
  tests/bundle/eZ/RichText/RendererTest.php
  tests/lib/eZ/FieldType/RichText/RichTextStorageTest.php
  tests/lib/eZ/REST/FieldTypeProcessor/RichTextProcessorTest.php
  tests/lib/eZ/RichText/Converter/LinkTest.php
  tests/lib/eZ/RichText/Converter/Render/EmbedTest.php
  tests/lib/eZ/RichText/Converter/Render/TemplateTest.php
Labels: Improvement, Ready for review

#37 EZP-28034: Refactored to depend on EzPlatformRestBundle
  composer.json
  src/lib/eZ/REST/FieldTypeProcessor/RichTextProcessor.php
Labels: Feature, QA approved, Ready for MERGE
