Repository ezsystems/ezplatform-richtext, pull requests merged in 2019-06, with the labels that each got.

#42 EZP-30517: Dropped Kernel BC layer and deprecated code
  src/bundle/DependencyInjection/Configuration/Parser/FieldType/RichText.php
  src/bundle/DependencyInjection/EzPlatformRichTextExtension.php
  src/bundle/EzPlatformRichTextBundle.php
  src/bundle/Resources/config/bc/aliases.yml
  src/bundle/Resources/config/form.yml
  src/bundle/eZ/RichText/Renderer.php
  src/lib/eZ/FieldType/RichText/RichTextStorage/Gateway/LegacyStorage.php
  src/lib/eZ/Persistence/Legacy/RichTextFieldValueConverter.php
  src/lib/eZ/RichText/RendererInterface.php
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  src/lib/eZ/RichText/Validator/Validator.php
  tests/bundle/DependencyInjection/Configuration/Parser/FieldType/RichTextTest.php
  tests/lib/eZ/FieldType/RichText/Gateway/LegacyStorageTest.php
  tests/lib/eZ/RichText/Converter/Xslt/BaseTest.php
  tests/lib/eZ/RichText/Validator/DocbookTest.php
Labels: Improvement

#43 EZP-30626: Change FieldType::getName() arguments
  src/lib/eZ/FieldType/RichText/Type.php
Labels: Ready for QA

#47 Changed variables to SF4 APP_ENV and APP_DEBUG
  .travis.yml
Labels: Ready for review

#45 EZP-30627: Unified Twig helpers naming
  src/bundle/Resources/views/RichText/content_fields.html.twig
  src/bundle/Templating/Twig/Extension/RichTextExtension.php
Labels: Improvement, Ready for review
