Repository ezsystems/ezplatform-richtext, pull requests merged in 2019-04, with the labels that each got.

#32 EZP-30166 : RichText Link converter emits warning during custom tag conversion
  src/lib/eZ/RichText/Converter/Link.php
  src/lib/eZ/RichText/Converter/Render/Template.php
  tests/lib/eZ/RichText/Converter/AggregateTest.php
  tests/lib/eZ/RichText/Converter/Render/TemplateTest.php
Labels: Bug, QA approved

#33 EZP-30386: [Alloy Editor] Custom Buttons
  src/bundle/DependencyInjection/Configuration.php
Labels: QA approved

#34 EZP-29876: New break lines disappear in Richtext while styled with custom styles
  src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
  src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/031-ezstyle.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/031-ezstyle.xml
Labels: Bug, QA approved

#35 EZP-29301: Added support for custom attributes on elements
  src/lib/eZ/RichText/Resources/schemas/docbook/ezpublish.rng
  src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
  src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/002-para.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/005-emphasis.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/006-emphasisStrong.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/007-emphasisUnderlined.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/008-orderedList.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/009-itemizedList.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/010-htmlInformaltable.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/011-htmlTable.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/014-link.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/015-subscript.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/016-superscript.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/019-emphasisStrikedthrough.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/020-blockquote.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/021-titleImplicitLevels.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/030-emphasisStrikedthroughDeleted.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/033-programlisting.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/custom_schemas/youtube.rng
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/002-para.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/005-emphasis.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/006-emphasisStrong.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/007-emphasisUnderlined.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/008-orderedList.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/009-itemizedList.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/010-htmlInformaltable.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/011-htmlTable.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/014-link.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/015-subscript.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/016-superscript.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/019-emphasisStrikedthrough.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/020-blockquote.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/021-titleImplicitLevels.lossy.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/030-emphasisStrikedthroughDeleted.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/033-programlisting.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/002-para.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/005-emphasis.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/006-emphasisStrong.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/007-emphasisUnderlined.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/008-orderedList.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/009-itemizedList.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/010-htmlInformaltable.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/011-htmlTable.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/014-link.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/015-subscript.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/016-superscript.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/019-emphasisStrikedthrough.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/020-blockquote.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/021-titleImplicitLevels.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/030-emphasisStrikedthroughDeleted.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/033-programlisting.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/custom_schemas/youtube.xsd
Labels: Feature, QA approved
