Repository ezsystems/ezplatform-richtext, pull requests merged in 2019-10, with the labels that each got.

#69 [Travis] Bumped solr version in tests to 3.0
  bin/.travis/prepare_unittest.sh
Labels: Ready for review

#71 [Travis] Updated Solr version in test matrix
  .travis.yml
Labels: Ready for review

#72 EZP-30959: Long URL overlaps "clear URL input" button in Online Editor
  src/bundle/Resources/public/scss/_link-edit.scss
Labels: Bug, QA approved

#68 EZP-30376 [Travis] Implementing reporting tool to behat automated tests
  .travis.yml
  .travis/rsa_allure.enc
Labels: Ready for MERGE

#73 EZP-30933: Added "link" Custom Tag attribute type
  src/bundle/DependencyInjection/Configuration.php
  tests/bundle/DependencyInjection/Configuration/ConfigurationTest.php
  tests/bundle/DependencyInjection/Fixtures/custom_tags/input/000-attribute-type-number.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/input/001-attribute-type-string.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/input/002-attribute-type-boolean.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/input/003-attribute-type-choice.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/input/004-attribute-type-link.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/output/000-attribute-type-number.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/output/001-attribute-type-string.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/output/002-attribute-type-boolean.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/output/003-attribute-type-choice.yaml
  tests/bundle/DependencyInjection/Fixtures/custom_tags/output/004-attribute-type-link.yaml
Labels: Bug, Improvement, QA approved

#78 EZP-31028: Fixed formatting involving soft return placed inside a Custom Template
  src/lib/eZ/RichText/Converter/Aggregate.php
  src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
  src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
  tests/lib/eZ/RichText/Converter/Xslt/BaseTest.php
  tests/lib/eZ/RichText/Converter/Xslt/DebugRenderer.php
  tests/lib/eZ/RichText/Converter/Xslt/DocbookToXhtml5OutputTest.php
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/031-ezstyle.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/031-ezstyle.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/024-template.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/025-templateInline.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/031-ezstyle.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/032-ezstyleinline.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/034-nestedTemplate.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/custom_schemas/custom.xsd
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/custom_schemas/youtube.xsd
Labels: Bug, QA approved, Ready for review

#77 EZP-31076: Skipped rendering hidden embedded content
  src/bundle/eZ/RichText/Renderer.php
  tests/bundle/eZ/RichText/RendererTest.php
Labels: Bug, QA approved
