Repository ezsystems/ezplatform-richtext, pull requests merged in 2019-11, with the labels that each got.

#82 EZP-30859: Cannot remove formatting after publication in RTE
  src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
Labels: QA approved, Ready for MERGE

#81 EZP-31010: Updated namespaces in ezplatform-richtext
  composer.json
  src/lib/Form/Mapper/RichTextFormMapper.php
Labels: Improvement, Ready for review

#83 EZP-31108: [CS] Enabled ezsystems/ezplatform-code-style package
  .php_cs
  composer.json
  src/bundle/eZ/RichText/Renderer.php
  src/lib/eZ/RichText/Converter/Render/Embed.php
  src/lib/eZ/RichText/ConverterDispatcher.php
  src/lib/eZ/RichText/XmlBase.php
Labels: Improvement

#86 EZP-31058: No new line can be inserted in RTE below custom tags
  src/bundle/Resources/public/js/OnlineEditor/plugins/base/ez-custom-tag-base.js
  src/bundle/Resources/public/js/OnlineEditor/plugins/base/ez-embed-base.js
  src/bundle/Resources/public/js/OnlineEditor/plugins/ez-custom-tag.js
Labels: Bug
