Repository ezsystems/ezplatform-richtext, pull requests merged in 2019-08, with the labels that each got.

#49 EZP-30646: Replaced SignalSlots with Events in integration tests setup factory
  tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php
Labels: QA approved

#55 EZP-30814: Removed Twig deprecations
  src/bundle/Resources/views/RichText/style/default.html.twig
  src/bundle/Resources/views/RichText/style/default_inline.html.twig
Labels: Improvement

#58 EZP-30829: Fixed container configuration to allow integration tests pass
  composer.json
  tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php
Labels: Bug, Ready for review

#57 [Composer] Added direct ezsystems/doctrine-dbal-schema dependency
  composer.json
Labels: Ready for review

#60 [Twig] Renamed RichTextExtension to RichTextConverterExtension
  src/bundle/Resources/config/templating.yaml
  src/bundle/Templating/Twig/Extension/RichTextConverterExtension.php
Labels: Improvement, Ready for MERGE

#59 EZP-30833: Aligned Field Type service tags to new naming convention
  src/bundle/Resources/config/form.yaml
  src/bundle/Resources/config/rest.yaml
  src/lib/eZ/settings/fieldtype_external_storages.yaml
  src/lib/eZ/settings/fieldtypes.yaml
  src/lib/eZ/settings/indexable_fieldtypes.yaml
  src/lib/eZ/settings/storage_engines/legacy/field_value_converters.yaml
Labels: Improvement, QA approved, Ready for MERGE

#53 EZP-30798: Provided YouTube, Facebook, and Twitter Custom Tags
  src/bundle/DependencyInjection/EzPlatformRichTextExtension.php
  src/bundle/Resources/config/prepend/ezpublish.yaml
  src/bundle/Resources/config/prepend/ezrichtext.yaml
  src/bundle/Resources/config/templating.yaml
  src/bundle/Resources/public/assets/images/custom_tags/admin/icons/facebook.svg
  src/bundle/Resources/public/assets/images/custom_tags/admin/icons/twitter.svg
  src/bundle/Resources/public/assets/images/custom_tags/admin/icons/video.svg
  src/bundle/Resources/translations/custom_tags.en.xlf
  src/bundle/Resources/views/themes/standard/ezrichtext/custom_tags/ezfacebook.html.twig
  src/bundle/Resources/views/themes/standard/ezrichtext/custom_tags/eztwitter.html.twig
  src/bundle/Resources/views/themes/standard/ezrichtext/custom_tags/ezyoutube.html.twig
  src/bundle/Templating/Twig/Extension/YoutubeIdExtractorExtension.php
  tests/bundle/Templating/Twig/Extension/YoutubeIdExtractorExtensionTest.php
Labels: Feature, QA approved

#61 EZP-30846: Dropped deprecated Symfony\Component\Config\Definition\Builder\TreeBuilder::root method calls
  src/bundle/DependencyInjection/Configuration.php
Labels: Improvement, QA approved

#54 EZP-30730: Narrowed "LF to <br>" XSLT to literallayout scope
  src/lib/eZ/RichText/Converter/Render/Template.php
  src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
  src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/eZ/RichText/Converter/Render/TemplateTest.php
  tests/lib/eZ/RichText/Converter/Render/_fixtures/template/input/08-line-breaks.xml
  tests/lib/eZ/RichText/Converter/Render/_fixtures/template/output/08-line-breaks.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/031-ezstyle.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/031-ezstyle.xml
Labels: Bug, QA approved

#52 EZP-30791: allow dashes in custom tag names
  src/bundle/DependencyInjection/Configuration.php
Labels: Bug, QA approved

#62 EZP-30798: Simplified DIC of Twig YoutubeIdExtractorExtension
  src/bundle/Resources/config/templating.yaml
Labels: Improvement, Ready for review

#44 EZP-30631: Fixed retrieving configuration (ezconfig) from DocBook tag
  src/lib/eZ/RichText/Converter/Render.php
  src/lib/eZ/RichText/Converter/Render/Template.php
  tests/lib/eZ/RichText/Converter/Render/EmbedTest.php
Labels: Bug, QA approved
