Repository ezsystems/ezplatform-richtext, pull requests merged in 2020-04, with the labels that each got.

#132 EZP-30940: Cannot remove table from richtext field
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-tableremove.js
Labels: Bug, QA approved

#133 EZP-31120: Image is not replaced in RTE/OE when publishing directly
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-imageupdate.js
Labels: Bug, QA approved

#129 EZP-29196: Handled line breaks inside itemized/ordered lists
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/008-orderedList.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/009-itemizedList.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/010-htmlInformaltable.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/008-orderedList.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/009-itemizedList.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/004-itemizedList.docbook.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/004-itemizedList.xhtml5.edit.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/005-orderedList.docbook.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/005-orderedList.xhtml5.edit.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/008-orderedList.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/009-itemizedList.xml
Labels: Bug, QA approved

#138 EZEE-3094: Added missing int casting in the RelationProcessor::getRelatedObjectIds
  src/lib/eZ/RichText/RelationProcessor.php
  tests/lib/eZ/RichText/RelationProcessorTest.php
Labels: Bug, QA approved

#137 EZP-31539: Link Validation error in Richtext Editor
  src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
Labels: Bug, QA approved, Ready for MERGE

#139 [Tests] Aligned SetupFactory to include PermissionService
  tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php
Labels: Bug, Ready for review

#140 EZP-29475: Changes for UDW title
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-embed.js
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-embedinline.js
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-embedupdate.js
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-image.js
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-imageupdate.js
  src/bundle/Resources/translations/alloy_editor.en.xliff
Labels: QA approved

#142 EZP-31547: Autowiring fails for CustomTag service when using 3rd party translator bundle
  src/bundle/Resources/config/ui/mappers.yaml
  src/lib/Configuration/UI/Mapper/CustomTag.php
  tests/lib/Configuration/UI/Mapper/CustomTagTest.php
Labels: Bug, QA approved

#141 EZP-30861: Handled line breaks inside headings
  src/lib/eZ/RichText/Resources/schemas/docbook/ezpublish.rng
  src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
  src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/docbook/001-title.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/001-title.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/output/001-title.xml
Labels: Bug, QA approved
