Repository ezsystems/ezplatform-richtext, pull requests merged in 2020-02, with the labels that each got.

#101 EZP-31293: Defined UI translation label for the custom CSS classes
  src/bundle/Resources/translations/online_editor.en.xlf
Labels: QA approved

#110 EZP-31137: Fixed styles dropdown when custom ones are in use for RTE
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-styleslistitem.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-custom-style.js
Labels: Bug, QA approved

#107 EZP-31272: Handled anchors generated with name attribute
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/008-anchor.docbook.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/008-anchor.xhtml5.edit.xml
Labels: Bug, QA approved, Ready for MERGE

#111 EZP-30485: Added validation for anchor link
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-anchoredit.js
  src/bundle/Resources/public/scss/_anchor-edit.scss
  src/bundle/Resources/public/scss/variables/colors.scss
  src/bundle/Resources/translations/alloy_editor.en.xlf
Labels: QA approved

#113 EZP-31380: Disable manage rows/cells buttons for table and row toolbars
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-table.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-table-cell.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-table-header.js
Labels: QA approved

#114 EZP-31371: Copying a web page link w/o protocol in a Word paragraph leads to a 404 error
  src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
Labels: Bug, QA approved, Ready for MERGE

#117 EZP-31409: Cannot select content item in link to image
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-imagelinkedit.js
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js
Labels: Bug, QA approved

#115 EZP-31356: Fixed styles dropdown selection on Firefox and Safari
  src/bundle/Resources/encore/ez.config.js
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-dropdown.js
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-styleslist.js
Labels: Bug, QA approved
