Repository ezsystems/ezplatform-richtext, pull requests merged in 2020-03, with the labels that each got.

#118 EZP-31066: Error when clicking the link in RTE
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-fixed.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-heading.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-paragraph.js
Labels: Bug, Ready for MERGE, Ready for QA

#87 EZP-31118: Introduced strict types for ContenteService
  src/bundle/eZ/RichText/Renderer.php
Labels: Bug, QA approved

#120 EZP-31118: Added missing int casting in the Converter\Link::convert
  src/lib/eZ/RichText/Converter/Link.php
Labels: Bug

#121 EZEE-3030: Links containing 'ezlocation` or 'ezcontent' keywords break RTE validation on paste
  src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
Labels: Bug, QA approved

#123 EZP-31220: Migrated codebase to Symfony 5
  composer.json
  src/bundle/Resources/config/default_settings.yaml
  src/bundle/Resources/config/fieldtype_services.yaml
  src/lib/eZ/RichText/Converter/Link.php
  src/lib/eZ/RichText/Converter/Render/Embed.php
  tests/bundle/DependencyInjection/Compiler/RichTextHtml5ConverterPassTest.php
  tests/bundle/DependencyInjection/Configuration/Parser/FieldType/RichTextTest.php
  tests/bundle/DependencyInjection/EzPlatformRichTextExtensionTest.php
  tests/bundle/eZ/RichText/RendererTest.php
  tests/lib/Configuration/UI/Mapper/CustomTagTest.php
  tests/lib/Validator/Constraints/RichTextValidatorTest.php
  tests/lib/eZ/FieldType/RichText/RichTextStorageTest.php
  tests/lib/eZ/FieldType/RichTextTest.php
  tests/lib/eZ/Persistence/Legacy/RichTextFieldValueConverterTest.php
  tests/lib/eZ/RichText/Converter/Render/EmbedTest.php
  tests/lib/eZ/RichText/Converter/Render/TemplateTest.php
  tests/lib/eZ/RichText/DOMDocumentFactoryTest.php
  tests/lib/eZ/RichText/Validator/CustomTagsValidatorTest.php
  tests/lib/eZ/RichText/Validator/InternalLinkValidatorTest.php
Labels: Ready for MERGE

#124 EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel
  README.md
  composer.json
  tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php
Labels: Improvement, Work in progress

#119 EZP-30545: Provided way to define buttons in AlloyEditor toolbars
  src/bundle/DependencyInjection/Configuration/Parser/FieldType/RichText.php
  src/bundle/Resources/config/prepend/ezpublish.yaml
  src/bundle/Resources/public/js/OnlineEditor/core/base-richtext.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-buttons.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-list.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base-table.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/base.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-custom-style.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-custom-tag.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-embed-inline.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-embed.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-formatted.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-heading.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-image-link.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-image.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-inline-custom-tag.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-link.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-paragraph.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-table-cell.js
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-text.js
  src/lib/Configuration/Provider/AlloyEditor.php
  tests/lib/Configuration/Provider/AlloyEditorTest.php
Labels: QA approved

#127 EZP-31499: Fixed generating routes for links in DocBook
  src/lib/eZ/RichText/Converter/Link.php
  tests/lib/eZ/RichText/Converter/AggregateTest.php
  tests/lib/eZ/RichText/Converter/LinkTest.php
Labels: Bug, Ready for review

#128 EZP-31512: Fixed extracting Search Fields from RichText
  .travis.yml
  src/lib/eZ/FieldType/RichText/SearchField.php
  tests/lib/eZ/FieldType/RichText/SearchFieldTest.php
Labels: Bug

#109 EZP-31129: Removed outdated URLs when storing Field data
  composer.json
  src/lib/eZ/FieldType/RichText/RichTextStorage.php
  src/lib/eZ/FieldType/RichText/RichTextStorage/Gateway.php
  tests/integration/eZ/API/RichTextFieldTypeIntegrationTest.php
  tests/lib/eZ/FieldType/RichText/RichTextStorageTest.php
Labels: Bug, QA approved

#130 EZP-31246: [Tests] Refactored tests not to rely on eZc Database
  tests/integration/eZ/SPI/RichTextFieldTypeIntegrationTest.php
  tests/lib/eZ/FieldType/RichText/Gateway/DoctrineStorageTest.php
Labels: Improvement
