Repository ezsystems/ezplatform-richtext, pull requests merged in 2020-01, with the labels that each got.

#99 EZP-30882: Added loading thumbnails to CoreSetupFactoryTrait
  tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php
Labels: Ready for review

#94 EZP-30033: Handled additional para inside itemized/ordered list
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/004-itemizedList.docbook.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/004-itemizedList.xhtml5.edit.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/005-orderedList.docbook.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/005-orderedList.xhtml5.edit.xml
Labels: Bug, QA approved, Ready for MERGE

#98 EZP-31245: Editing link in paragraph containing more lines ends up with JS error
  src/bundle/Resources/public/js/OnlineEditor/toolbars/config/ez-image-link.js
Labels: QA approved

#93 EZP-30129: Handled bold & italic styles when converting from OE format to DocBook
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/003-inlinestyles.docbook.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/003-inlinestyles.xhtml5.edit.xml
Labels: QA approved

#100 EZP-30130: Added handling of soft breaks inside nested formatting within paragraphs
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/006-paragraph.docbook.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/006-paragraph.xhtml5.edit.xml
Labels: Bug, QA approved

#96 EZP-31187: Changed margins for embedded
  src/bundle/Resources/public/scss/_alloyeditor-ez.scss
Labels: QA approved

#97 EZP-31188: Change padding in custom tag buttons
  src/bundle/Resources/public/scss/_custom-tag.scss
Labels: QA approved

#95 Ported fix for EZP-29958 and EZP-29984 from kernel
  src/lib/eZ/FieldType/RichText/SearchField.php
  src/lib/eZ/FieldType/RichText/Type.php
  src/lib/eZ/Persistence/Legacy/RichTextFieldValueConverter.php
Labels: QA approved

#103 EZP-31056: Link is added to the text in RTE despite not choosing any content via UDW
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-imagelinkedit.js
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js
Labels: Bug, QA approved, Ready for MERGE

#102 EZEE-2914: Custom inline style does not update textarea after click on
  src/bundle/Resources/encore/ez.config.js
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-styleslistitem.js
Labels: Bug, QA approved

#104 EZP-31295: Unable to use default empty custom CSS class in the OE
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-attributes-update.js
Labels: Bug

#88 EZP-31321: Replaced zero-width space with oe-upcast-placeholder
  src/lib/eZ/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/023-embedInline.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/035-itemizedListWithNestedElements.xml
Labels: Improvement, QA approved

#105 EZP-31321: Dropped injecting zero-width space into ezembed(inline) elements
  src/bundle/Resources/public/js/OnlineEditor/plugins/ez-custom-tag.js
  src/bundle/Resources/public/js/OnlineEditor/plugins/ez-embed.js
Labels: Bug

#108 EZP-31278: Removed usage of the obsolete RegisterLimitationTypePass
  tests/integration/eZ/API/SetupFactory/CoreSetupFactoryTrait.php
Labels: Improvement

#106 EZP-30222: Handled tables copied from external sources
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/007-table.docbook.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/007-table.xhtml5.edit.xml
Labels: Bug, QA approved
