Repository ezsystems/ezplatform-richtext, pull requests merged in 2020-05, with the labels that each got.

#144 [Travis] Changed notification key after rebranding
  .travis.yml
Labels: Ready for review

#146 EZP-31626: Fixed rendering of embed locations
  src/bundle/eZ/RichText/Renderer.php
Labels: QA approved

#143 EZP-31612: use custom tag choice labels
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-customtag-update.js
Labels: QA approved, Ready for MERGE

#145 EZP-1308: Update design for custom tags popups
  src/bundle/DependencyInjection/EzPlatformRichTextExtension.php
  src/bundle/Resources/config/bazinga_js_translation.yaml
  src/bundle/Resources/config/prepend/ezrichtext.yaml
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-customtag-update.js
  src/bundle/Resources/public/js/OnlineEditor/core/ez-custom-tags.js
  src/bundle/Resources/public/scss/_alloyeditor-ez.scss
  src/bundle/Resources/public/scss/alloyeditor.scss
  src/bundle/Resources/public/scss/functions/checkbox-switcher.scss
  src/bundle/Resources/public/scss/variables/colors.scss
  src/bundle/Resources/translations/alloy_editor.en.xliff
  src/bundle/Resources/views/themes/standard/ezrichtext/custom_tags/ezyoutube.html.twig
Labels: Fast-forward merge, Improvement, QA approved

#149 EZP-31641: Unable to manage links in table cells
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-linkedit.js
Labels: QA approved
