Repository ezsystems/ezplatform-richtext, pull requests merged in 2023-07, with the labels that each got.

#234 [PHPStan] Added new issues to PHPStan baseline after the release
  phpstan-baseline.neon
Labels: Bug, Ready for review

#235 IBX-6134: Changed ANCHOR_PATTERN to be compatible with xml:id because cannot have : character
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-anchoredit.js
Labels: Bug, QA approved

#236 IBX-6136: Changed value validation logic for anchor
  src/bundle/Resources/public/js/OnlineEditor/buttons/ez-btn-anchoredit.js
Labels: Bug, QA approved

#233 IBX-5961: Fixed validation error due to not accepted TextAlign value
  src/lib/eZ/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/009-ezxhtmlTextalignInvalid.docbook.xml
  tests/lib/eZ/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/009-ezxhtmlTextalignInvalid.xhtml5.edit.xml
Labels: QA approved
